# Generated by Django 2.2.7 on 2019-12-06 18:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


utc = datetime.timezone.utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191128_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateField(default=datetime.datetime(
                2019, 12, 6, 18, 5, 21, 837002, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post'),
        ),
    ]
